---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python
# Exercise 1
```

In [2]:
import numpy as np

In [3]:
x = np.arange(1, 11, 1)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python
# Exercise 2
```

---

In [4]:
x = np.zeros((3, 3))
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python
# Exercise 3
```

---

In [5]:
x = np.linspace(0, 5, 10)
x

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
# Exercise 4
```

---

In [6]:
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python
# Exercise 5
```

---

In [7]:
x = np.random.random((4, 4))
x

array([[0.78074681, 0.23280685, 0.70224381, 0.78665127],
       [0.62615004, 0.94704147, 0.31031067, 0.80517999],
       [0.54507939, 0.09301671, 0.7390882 , 0.49798728],
       [0.39523095, 0.56599324, 0.90805624, 0.31916473]])

### Exercise 6:
Find the shape of a NumPy array.

```python
# Exercise 6
```

---

In [8]:
x.shape

(4, 4)

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
# Exercise 7
```

---

In [14]:
x = np.random.randint(1, 10, size=16)
y = x.reshape((4, 4))
x, y

(array([4, 6, 6, 4, 2, 3, 4, 6, 6, 8, 1, 2, 8, 1, 6, 5]),
 array([[4, 6, 6, 4],
        [2, 3, 4, 6],
        [6, 8, 1, 2],
        [8, 1, 6, 5]]))

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python
# Exercise 8
```

---

In [15]:
x.dtype

dtype('int64')

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python
# Exercise 9
```

---

In [18]:
x = np.arange(1, 101, 1)
even = lambda value: value%2==0
even_vectorize = np.vectorize(even)
x[even(x)]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python
# Exercise 10
```

---

In [19]:
x = np.random.randint(10, 50, size=(6, 6))
x

array([[47, 10, 39, 27, 14, 24],
       [37, 26, 15, 18, 37, 40],
       [47, 31, 22, 21, 32, 36],
       [45, 18, 28, 42, 15, 40],
       [31, 26, 46, 39, 17, 39],
       [24, 12, 37, 47, 24, 42]])

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python
# Exercise 11
```

---

In [68]:
x = np.random.random((6, 6))
x[1:, 0:2]

array([[0.17604213, 0.45851421],
       [0.01463488, 0.84876407],
       [0.33867913, 0.09465904],
       [0.29383156, 0.65572674],
       [0.78486672, 0.39341911]])

### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python
# Exercise 12
```

---

In [20]:
np.sum(x)

1095

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python
# Exercise 13
```

---

In [21]:
np.mean(x), np.median(x), np.std(x)

(30.416666666666668, 31.0, 11.113992681900298)

### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python
# Exercise 14
```

---

In [22]:
np.max(x), np.min(x)

(47, 10)

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
# Exercise 15
```

---

In [42]:
np.random.seed(10)

In [46]:
np.random.rand(4, 4)

array([[0.90864888, 0.31923609, 0.09045935, 0.30070006],
       [0.11398436, 0.82868133, 0.04689632, 0.62628715],
       [0.54758616, 0.819287  , 0.19894754, 0.8568503 ],
       [0.35165264, 0.75464769, 0.29596171, 0.88393648]])

In [24]:
x = np.random.randint(1, 10, size=20)
np.argmax(x)

6

### Exercise 16:
Create a NumPy array and reverse its elements.

```python
# Exercise 16
```

---

In [35]:
y = x[::-1]
y, x

(array([7, 9, 9, 9, 2, 7, 8, 3, 1, 9, 9, 2, 1, 9, 8, 8, 1, 1, 3, 8]),
 array([8, 3, 1, 1, 8, 8, 9, 1, 2, 9, 9, 1, 3, 8, 7, 2, 9, 9, 9, 7]))

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python
# Exercise 17
```

---

In [38]:
x = np.random.randint(1, 10, size=(3, 3))
y = np.random.randint(1, 10, size=(3, 3))
x * y

array([[ 7, 49, 32],
       [42,  8,  5],
       [ 8, 12, 12]])

### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
# Exercise 18
```

---

In [48]:
x = np.random.randint(1, 10, size=10)
y = np.zeros((len(x), len(x)))
for i in range(len(x)):
    for j in range(len(x)):
        if i==j:
            y[i,j] = x[i]
y, x

(array([[2., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 3., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 9., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 6., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 3., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 8., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 4., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 5.]]),
 array([2, 3, 9, 6, 1, 3, 8, 4, 1, 5]))

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
# Exercise 19
```

---

In [50]:
y = np.random.randint(1, 10, size=(3, 3))
x = np.random.randint(1, 10, size=(3, 3))
np.dot(x, y)

array([[38, 60, 70],
       [58, 42, 47],
       [56, 44, 66]])

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python
# Exercise 20
```

---

In [61]:
x.reshape(np.prod(x.shape))

array([7, 1, 6, 2, 4, 7, 6, 6, 2])

### Exercise 21:
Stack two NumPy arrays vertically.

```python
# Exercise 21
```

---

In [75]:
x = np.random.randint(1, 10, size=(3, 3))
y = np.random.randint(1, 10, size=(3, 3))
# np.stack((x, y))
np.stack((x, y))

array([[[9, 1, 7],
        [8, 6, 2],
        [3, 7, 2]],

       [[6, 9, 1],
        [4, 7, 4],
        [1, 3, 9]]])

In [74]:
np.stack?

### Exercise 22:
Stack two NumPy arrays horizontally.

```python
# Exercise 22
```

---

In [76]:
np.stack((x, y), axis=1)

array([[[9, 1, 7],
        [6, 9, 1]],

       [[8, 6, 2],
        [4, 7, 4]],

       [[3, 7, 2],
        [1, 3, 9]]])

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python
# Exercise 23
```

---

In [79]:
x = np.random.randint(1, 5, (5, 10))
x[:,0:4], x[0:4,4:], x[4:,4:]

(array([[4, 3, 3, 1],
        [4, 4, 2, 3],
        [3, 1, 2, 3],
        [4, 1, 4, 3],
        [2, 1, 3, 1]]),
 array([[3, 4, 4, 1, 4, 3],
        [2, 1, 4, 3, 2, 3],
        [4, 4, 4, 1, 4, 3],
        [2, 2, 2, 1, 3, 4]]),
 array([[3, 1, 1, 1, 3, 2]]))

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python
# Exercise 24
```

---

In [80]:
np.round(np.random.random((3, 4)), decimals=2)

array([[0.21, 0.14, 0.7 , 0.06],
       [0.26, 0.51, 1.  , 0.15],
       [0.45, 0.6 , 0.1 , 0.29]])

### Exercise 25:
Find the unique elements of a NumPy array.

```python
# Exercise 25
```

---

In [83]:
x = np.random.randint(1, 5, (10, 5))
x, np.unique(x)

(array([[1, 4, 4, 4, 1],
        [4, 3, 1, 4, 2],
        [2, 1, 1, 4, 2],
        [3, 2, 1, 3, 4],
        [2, 2, 4, 2, 3],
        [4, 4, 2, 1, 3],
        [1, 2, 4, 1, 3],
        [1, 4, 1, 4, 1],
        [1, 1, 3, 2, 3],
        [4, 1, 1, 3, 1]]),
 array([1, 2, 3, 4]))

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
# Exercise 26
```

---

In [6]:
x = np.random.randint(1, 20, (4, 6))
specific_value = 8
x[x<specific_value] = 8
x

array([[13, 15, 15, 19,  8, 12],
       [17,  8,  9, 12, 16, 13],
       [ 8, 18, 14,  9, 17,  8],
       [ 8, 10, 16,  8,  8, 15]])

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python
# Exercise 27
```

---

In [7]:
x = np.array([1, 2, 3, 4, 5])
y = np.cumsum(x)
x, y

(array([1, 2, 3, 4, 5]), array([ 1,  3,  6, 10, 15]))

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
# Exercise 28
```

---

In [11]:
x = np.random.randint(0, 4, (4, 5))
# np.count_nonzero(x)
np.count_nonzero(x, axis=1)

array([3, 4, 4, 5])

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
# Exercise 29
```

---

In [13]:
x = np.random.randint(1, 20, 20)
np.sort(x)

array([ 1,  1,  2,  4,  4,  4,  4,  5,  6,  6,  7,  7,  8, 12, 12, 16, 17,
       17, 17, 18])

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
# Exercise 30
```

---

In [15]:
x = np.random.randint(1, 10, (3, 3))
row_wise = np.sum(x, axis=1)
column_wise = np.sum(x, axis=0)
x, row_wise, column_wise

(array([[4, 3, 9],
        [7, 9, 2],
        [9, 1, 1]]),
 array([16, 18, 11]),
 array([20, 13, 12]))

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python
# Exercise 31
```

---

In [17]:
y = (x - x.min())/(x.max() - x.min())
x, y

(array([[4, 3, 9],
        [7, 9, 2],
        [9, 1, 1]]),
 array([[0.375, 0.25 , 1.   ],
        [0.75 , 1.   , 0.125],
        [1.   , 0.   , 0.   ]]))

### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
# Exercise 32
```

---

In [19]:
np.dot(x, y)

array([[12.75 ,  4.   ,  4.375],
       [11.375, 10.75 ,  8.125],
       [ 5.125,  3.25 ,  9.125]])

### Exercise 33:
Find the trace of a square NumPy matrix.

```python
# Exercise 33
```

---

In [20]:
np.trace(x)

14

### Exercise 34:
Create a 2D array and swap two rows.

```python
# Exercise 34
```

---

In [24]:
x = np.array([[1, 3], [2, 4]])
print(f'no swaping:')
print(x)
x[[0, 1]] = x[[1, 0]]
print(f'swaping first and second row:')
print(x)

no swaping:
[[1 3]
 [2 4]]
swaping first and second row:
[[2 4]
 [1 3]]


### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python
# Exercise 35
```

---

In [28]:
array = np.array([1, 2, 3, 4, 5])

# column_vector = array[:, np.newaxis]
column_vector = array.reshape((array.shape[0], 1))

print("Original 1D Array:\n", array)
print("Column Vector:\n", column_vector)


Original 1D Array:
 [1 2 3 4 5]
Column Vector:
 [[1]
 [2]
 [3]
 [4]
 [5]]


### Exercise 36:
Find the determinant of a 3x3 matrix.

```python
# Exercise 36
```

---

In [30]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(x)

0.0

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python
# Exercise 37
```

---

In [33]:
x = np.array([[1, 2], [4, 5]])

# Compute the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(x)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [-0.46410162  6.46410162]
Eigenvectors:
 [[-0.80689822 -0.34372377]
 [ 0.59069049 -0.9390708 ]]


### Exercise 38:
Solve a system of linear equations using NumPy.

```python
# Exercise 38
```

---

In [35]:
# solve AX = B
A= np.array([[1, 2], [4, 5]])
B = np.array([3, 1])

# solutions
np.linalg.solve(A, B)

array([-4.33333333,  3.66666667])

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

In [ ]:
original_array = np.array([[1, 2], [3, 4]])

# Define the parameters for the Gaussian noise
mean = 0
std_dev = 0.1

# gaussian noise matrix
noise = np.random.normal()

print("Original array:\n", original_array)
print("Noise:\n", noise)
print("Noisy array:\n", noisy_array)


### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python
# Exercise 40
```

---

In [37]:
x = np.random.randint(1, 10, (4, 4))
diag_elements = np.diag(x)
x, diag_elements

(array([[6, 1, 9, 9],
        [6, 3, 3, 4],
        [6, 2, 6, 7],
        [5, 9, 2, 8]]),
 array([6, 3, 6, 8]))

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

In [40]:
x = np.random.randint(1, 10, 100)
cliped_values = np.clip(x, 10, 50)
cliped_values, x

(array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
        10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10]),
 array([3, 2, 6, 7, 8, 5, 9, 8, 7, 7, 5, 5, 4, 5, 6, 7, 2, 4, 3, 5, 7, 5,
        8, 8, 8, 7, 1, 7, 2, 7, 6, 5, 7, 3, 8, 2, 7, 6, 1, 6, 3, 9, 5, 8,
        8, 8, 9, 4, 9, 6, 5, 8, 8, 5, 2, 4, 9, 3, 8, 5, 2, 7, 8, 9, 2, 8,
        6, 2, 5, 4, 2, 2, 6, 3, 4, 1, 3, 8, 1, 4, 6, 6, 2, 4, 4, 4, 8, 9,
        8, 7, 5, 4, 5, 5, 1, 8, 8, 7, 9, 9]))

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---